# Generated by Django 3.0.8 on 2020-07-18 19:15

from django.db import migrations

import requests

def import_albums(apps, schema_editor):
    Album = apps.get_model('albums', 'Album')
    User = apps.get_model('users', 'User')

    url = "https://jsonplaceholder.typicode.com/albums"
    response = requests.get(url)
    api_albums = response.json()

    created_albums = []

    for album in api_albums:
        user = User.objects.get(pk=album.get("userId"))
        created_albums.append(Album(
            owner=user,
            title=album.get("title")
        ))

    Album.objects.bulk_create(created_albums)


def import_photos(apps, schema_editor):
    Photo = apps.get_model('albums', 'Photo')
    User = apps.get_model('users', 'User')

    url = "https://jsonplaceholder.typicode.com/photos"
    response = requests.get(url)
    api_photos = response.json()

    created_photos = []

    for photo in api_photos:
        created_photos.append(Photo(
            album_id=photo.get("albumId"),
            title=photo.get("title"),
            url=photo.get("url"),
            thumbnail_url=photo.get("thumbnailUrl")
        ))

    Photo.objects.bulk_create(created_photos)


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('users', '0002_auto_20200718_1547')
    ]

    operations = [
        migrations.RunPython(import_albums),
        migrations.RunPython(import_photos)
    ]
