# Generated by Django 3.0.8 on 2020-07-18 15:47

from django.contrib.auth import get_user_model
from django.db import migrations
from faker import Factory

faker = Factory.create()

def create_users(apps, schema_editor):
    User = get_user_model()
    users = []

    User.objects.create_superuser(
        name="Desafio",
        email="desafio@frwk.com.br",
        password="12345"
    )

    for index in range(0, 9):
        users.append(User.objects.create_user(
            name=faker.name(),
            email=faker.email(),
            password="12345"
        ))


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
