# Generated by Django 3.0.8 on 2020-07-18 15:25

import requests
from django.contrib.auth import get_user_model
from django.db import migrations


def import_todos(apps, schema_editor):
    Todo = apps.get_model('todos', 'Todo')
    User = apps.get_model('users', 'User')

    url = "https://jsonplaceholder.typicode.com/todos"
    response = requests.get(url)
    api_todos = response.json()

    created_todos = []

    for todo in api_todos:
        user = User.objects.get(pk=todo.get("userId"))
        created_todos.append(Todo(
            owner=user,
            completed=todo.get("completed"),
            title=todo.get("title")
        ))

    Todo.objects.bulk_create(created_todos)


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
        ('users', '0002_auto_20200718_1547')
    ]

    operations = [
        migrations.RunPython(import_todos),
    ]
