# Generated by Django 3.0.8 on 2020-07-18 13:33

import requests
from django.db import migrations


def import_comments(apps, schema_editor):
    Comment = apps.get_model('posts', 'Comment')

    url = "https://jsonplaceholder.typicode.com/comments"
    response = requests.get(url)
    api_comments = response.json()

    created_comments = []

    for comment in api_comments:
        created_comments.append(Comment(
            post_id=comment.get("postId"),
            body=comment.get("body"),
            email=comment.get("email"),
            name=comment.get("name")
        ))

    Comment.objects.bulk_create(created_comments)


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.RunPython(import_comments),
    ]
